#!/usr/bin/env python3
"""Generate Mihomo and Quantumult X rule files from rules/source.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "rules" / "source.json"
CLASH_DIR = ROOT / "clash" / "rules"
QX_FILE = ROOT / "quantumultx" / "managed.list"

TYPE_TO_QX = {
    "DOMAIN": "host",
    "DOMAIN-SUFFIX": "host-suffix",
    "IP-CIDR": "ip-cidr",
    "IP-CIDR6": "ip6-cidr",
}


def load_source() -> dict:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    if data.get("version") != 2:
        raise ValueError("Unsupported rules/source.json version")
    if not isinstance(data.get("apps"), list) or not data["apps"]:
        raise ValueError("rules/source.json must contain a non-empty apps list")
    return data


def validate(data: dict) -> None:
    seen_ids: set[str] = set()
    forbidden = (
        "gemini.google.com",
        "google.com",
        "googleapis.com",
        "gstatic.com",
        "googleusercontent.com",
        "youtube.com",
        "googlevideo.com",
        "ytimg.com",
        "ggpht.com",
    )

    for app in data["apps"]:
        app_id = app["id"]
        if app_id in seen_ids:
            raise ValueError(f"Duplicate app id: {app_id}")
        seen_ids.add(app_id)
        if not app.get("qx_policy"):
            raise ValueError(f"Missing qx_policy for {app_id}")

        seen_rules: set[tuple[str, str]] = set()
        for rule in app.get("rules", []):
            rule_type = rule["type"]
            value = rule["value"].strip().lower()
            if rule_type not in TYPE_TO_QX:
                raise ValueError(f"Unsupported rule type: {rule_type}")
            key = (rule_type, value)
            if key in seen_rules:
                raise ValueError(f"Duplicate rule in {app_id}: {key}")
            seen_rules.add(key)

            if any(value == item or value.endswith("." + item) for item in forbidden):
                raise ValueError(
                    f"Forbidden shared Google/Gemini/YouTube rule in {app_id}: {value}"
                )


def clash_line(rule: dict) -> str:
    parts = [rule["type"], rule["value"]]
    if rule.get("no_resolve"):
        parts.append("no-resolve")
    return "  - " + ",".join(parts)


def qx_line(rule: dict, policy: str) -> str:
    qx_type = TYPE_TO_QX[rule["type"]]
    parts = [qx_type, rule["value"], policy]
    if rule.get("no_resolve"):
        parts.append("no-resolve")
    return ",".join(parts)


def generate(data: dict) -> None:
    CLASH_DIR.mkdir(parents=True, exist_ok=True)
    QX_FILE.parent.mkdir(parents=True, exist_ok=True)

    qx_lines = [
        "# AUTO-GENERATED from rules/source.json. Do not edit this file directly.",
        "# Gemini, shared Google services and YouTube are intentionally excluded.",
        "",
    ]

    for app in data["apps"]:
        app_id = app["id"]
        clash_lines = [
            "payload:",
            f"  # {app['title']}",
            *[clash_line(rule) for rule in app["rules"]],
            "",
        ]
        (CLASH_DIR / f"{app_id}.yaml").write_text(
            "\n".join(clash_lines), encoding="utf-8"
        )

        qx_lines.append(f"# {app['title']}")
        qx_lines.extend(qx_line(rule, app["qx_policy"]) for rule in app["rules"])
        qx_lines.append("")

    # Older bootstraps may still request this provider. Keep it harmless.
    (CLASH_DIR / "gemini.yaml").write_text("payload: []\n", encoding="utf-8")
    QX_FILE.write_text("\n".join(qx_lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    data = load_source()
    validate(data)
    generate(data)


if __name__ == "__main__":
    main()
